export function DisclaimerSection() {
  return (
    <section className="print:break-inside-avoid">
      <h2 className="text-xl font-bold mb-4">⚠️ Important Disclaimers</h2>

      <div className="space-y-4 text-sm text-muted-foreground bg-muted/30 p-4 rounded-lg border print:bg-gray-100 print:border-gray-300">
        <p>
          <strong>Not Financial Advice:</strong> This report is for
          informational and educational purposes only. It does not constitute
          investment advice, a recommendation, or an offer to buy or sell any
          security.
        </p>

        <p>
          <strong>Forward-Looking Statements:</strong> Valuation models involve
          assumptions about future performance, which are inherently uncertain.
          Actual results may differ materially from projections.
        </p>

        <p>
          <strong>Data Accuracy:</strong> While we strive for accuracy,
          financial data may contain errors or delays. Always verify critical
          information with official sources (e.g., company filings, stock
          exchanges).
        </p>

        <p>
          <strong>Risk Disclosure:</strong> Investing in securities involves
          risk, including potential loss of principal. Past performance is not
          indicative of future results. Consider your risk tolerance and consult
          a qualified financial advisor before making investment decisions.
        </p>

        <p className="pt-2 border-t text-xs">
          Report generated by StockAnalyzer •{" "}
          {new Date().toLocaleDateString("id-ID", {
            year: "numeric",
            month: "long",
            day: "numeric",
            hour: "2-digit",
            minute: "2-digit",
          })}{" "}
          • Data as of report generation time
        </p>
      </div>
    </section>
  );
}
